# Change these first
owner: chain-courses # Your GitHub username
repo: exchanges # Your Github repository name

# Add your sites here
sites:
  - name: PayPal
    url: https://paypal.com
  - name: Coinbase
    url: https://www.coinbase.com
  - name: Kraken
    url: https://www.kraken.com/en-us/
  - name: Bittrex
    url: https://bittrex.com/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: exchanges.chain.courses
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Crypto Exchanges Upptime
  introTitle: "James Gan's Crypto Exchange Uptime Tracker"
  introMessage: This is an Upptime instance tracking various Crypto exchanges, if you like it, please check out the Blockchain course I created in my Master's program at Georgia Tech at https://chain.courses to learn about Blockchain and Cryptocurrency!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Chain.Courses
      href: https://chain.courses/
    - title: James
      href: https://bellevue.tech

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
